server:
  port: 9001
spring:
  application:
    name: api-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka
    fetch-registry: true
    register-with-eureka: true